---
dictionaryDefinitions:
    - name: 'local-dictionary'
      path: './local-dictionary.txt'
      addWords: true
dictionaries:
    - 'local-dictionary'
ignorePaths:
    - 'node_modules'
    - '/local-dictionary.txt'
